import { Character } from '../types/character';

export const INITIAL_CHARACTERS: Character[] = [
  {
    id: '1',
    name: 'ChromeT',
    gs: 2762,
    classType: 'Templar',
    priority: 'High',
    deus: 9,
    arkanis: 8,
    gearTarget: 'Cradle',
    accessoryTarget: 'Dramata',
    missingGearCount: 5,
    missingAccessoryCount: 7,
    useManualMissingCounts: true,
    checklist: {
      wpn: false,
      earL: false,
      earR: true,
      neck: false,
      ringL: false,
      ringR: false,
      guards: false,
      breastplate: false,
      greaves: false,
      helm: false,
      pauldrons: false,
      gloves: false,
      boots: false,
      cloak: true,
    },
    notes: 'Main Tank. Priority target is Cradle of Crimson Shadow.',
  },
  {
    id: '2',
    name: 'Roxarika',
    gs: 2664,
    classType: 'Templar',
    priority: 'Critical',
    deus: 8,
    arkanis: 8,
    gearTarget: 'Kromede',
    accessoryTarget: 'Nuakum',
    missingGearCount: 1,
    missingAccessoryCount: 4,
    useManualMissingCounts: true,
    checklist: {
      wpn: false,
      earL: true,
      earR: true,
      neck: true,
      ringL: true,
      ringR: false,
      guards: false,
      breastplate: false,
      greaves: true,
      helm: true,
      pauldrons: true,
      gloves: false,
      boots: false,
      cloak: true,
    },
    notes: 'Secondary Tank.',
  },
  {
    id: '3',
    name: 'Averroes',
    gs: 2621,
    classType: 'Gladiator',
    priority: 'Critical',
    deus: 8,
    arkanis: 8,
    gearTarget: 'Kromede',
    accessoryTarget: 'Nuakum',
    missingGearCount: 2,
    missingAccessoryCount: 7,
    useManualMissingCounts: true,
    checklist: {
      wpn: true,
      earL: true,
      earR: true,
      neck: true,
      ringL: true,
      ringR: false,
      guards: false,
      breastplate: false,
      greaves: true,
      helm: true,
      pauldrons: true,
      gloves: true,
      boots: true,
      cloak: true,
    },
    notes: 'Primary Melee DPS.',
  },
  {
    id: '4',
    name: 'Crosley',
    gs: 2584,
    classType: 'Ranger',
    priority: 'Medium',
    deus: 6,
    arkanis: 6,
    gearTarget: 'Kromede',
    accessoryTarget: 'Nuakum',
    missingGearCount: 4,
    missingAccessoryCount: 6,
    useManualMissingCounts: true,
    checklist: {
      wpn: false,
      earL: false,
      earR: true,
      neck: false,
      ringL: true,
      ringR: false,
      guards: false,
      breastplate: false,
      greaves: false,
      helm: false,
      pauldrons: true,
      gloves: true,
      boots: false,
      cloak: false,
    },
    notes: 'Ranged Physical DPS.',
  },
  {
    id: '5',
    name: 'Seneca',
    gs: 2437,
    classType: 'Templar',
    priority: 'Low',
    deus: 7,
    arkanis: 7,
    gearTarget: 'Urugugu',
    accessoryTarget: 'Vakron',
    missingGearCount: 1,
    missingAccessoryCount: 1,
    useManualMissingCounts: true,
    checklist: {
      wpn: true,
      earL: true,
      earR: true,
      neck: true,
      ringL: true,
      ringR: true,
      guards: false,
      breastplate: false,
      greaves: true,
      helm: true,
      pauldrons: true,
      gloves: true,
      boots: true,
      cloak: true,
    },
  },
  {
    id: '6',
    name: 'Cicero',
    gs: 2412,
    classType: 'Cleric',
    priority: 'Extreme',
    deus: 7,
    arkanis: 7,
    gearTarget: 'Urugugu',
    accessoryTarget: 'Vakron',
    missingGearCount: 3,
    missingAccessoryCount: 8,
    useManualMissingCounts: true,
    checklist: {
      wpn: true,
      earL: true,
      earR: true,
      neck: true,
      ringL: true,
      ringR: true,
      guards: true,
      breastplate: true,
      greaves: true,
      helm: true,
      pauldrons: true,
      gloves: true,
      boots: true,
      cloak: true,
    },
    notes: 'Main Healer. All gear checked but still tracking targets.',
  },
  {
    id: '7',
    name: 'Nathaniel',
    gs: 2407,
    classType: 'Templar',
    priority: 'High',
    deus: 6,
    arkanis: 5,
    gearTarget: 'Urugugu',
    accessoryTarget: 'Vakron',
    missingGearCount: 1,
    missingAccessoryCount: 2,
    useManualMissingCounts: true,
    checklist: {
      wpn: false,
      earL: false,
      earR: true,
      neck: false,
      ringL: true,
      ringR: false,
      guards: true,
      breastplate: false,
      greaves: true,
      helm: true,
      pauldrons: false,
      gloves: false,
      boots: false,
      cloak: false,
    },
  },
  {
    id: '8',
    name: 'Astarco',
    gs: 2400,
    classType: 'Chanter',
    priority: 'Medium',
    deus: 7,
    arkanis: 7,
    gearTarget: 'Kromede',
    accessoryTarget: 'Nuakum',
    missingGearCount: 4,
    missingAccessoryCount: 7,
    useManualMissingCounts: true,
    checklist: {
      wpn: false,
      earL: false,
      earR: false,
      neck: false,
      ringL: false,
      ringR: false,
      guards: false,
      breastplate: false,
      greaves: false,
      helm: false,
      pauldrons: false,
      gloves: false,
      boots: false,
      cloak: false,
    },
    notes: 'Support Buffer.',
  },
];
